### ISSUE TITLE
Sub tree solving

### ISSUE THREAD

**Issue by Jona-Gold** [TinkeringCode/PokerRL#1]
Hey, 

I was wondering how would one go about solving a game of NLTH on only a few subsets of a full game tree.  
For example, how could I limit the poker engine used when training CFR; so that lets say,  the flop 2c2h2d always gets dealt. Another example would be to have a fixed starting hand.

What I am trying to do is this: find flop textures that are similar and group them together.  For that I would like to see how each hand acts on particular board and so on.

Another completly seperate thing I noticed. You have a DLL for evaluating hands, is it possible to get a source code for that?  Some variants of poker have smaller decks and rules.
For example [ 6+ No limit holdem](https://www.pokernews.com/poker-rules/six-plus-hold-em.htm), in this game players play with 36 card deck. And because of that hand rankings are different; Flush beats a full house etc. 

Thank you,
Jonas

**Comment by TinkeringCode** [comment]
Hi Jonas,

Subtree solving with CFR is not directly supported (feel free to make a PR!). However, for sampling-based methods, this can be done with the RL interface by setting the state of the environment to a manually created state dictionary.

The source of the C++ handeval source code has purposefully not been released for exactly this reason. I particularly tried to make it hard to extend to 6+ NLH. Why? Because this library is for research and 6+ NLH does not really seem like an interesting research env, while it is played for a lot of money online. Hence, there is no gain but a lot of risk for non-scientific use. I hope you understand my reasoning here.

Best,
Eric
