### ISSUE TITLE
BR doesn't work with FlopHoldem 

### ISSUE THREAD

**Issue by SavvaI** [TinkeringCode/PokerRL#3]
I tried to evaluate my agent's exploitability with Flop5Holdem, so i changed eval_methods to br,    but when I tried to launch it, program freezed on Creating BR Evaluator...

**Comment by TinkeringCode** [comment]
Hi!

I see you already closed this, thanks. For other users that read this: It is not meant to work.

Why? Because BR of Flop5Holdem is very expensive. Even more so without any domain-specific invariance optimizations. Moreover, including this would increase the potential for non-scientific and non-educational use, which I don't want. I recommend using LBR and RL-BR in 5FHP and bigger games.

Best Eric
